### ISSUE TITLE
Conflictos

### ISSUE THREAD

**Issue by jurricariet** [d4t4tur/DT4_perfiles#1]
Siguen figurando al inicio y en los gráficos
![image](https://user-images.githubusercontent.com/44036018/127221580-8804836a-2933-48ae-8713-f476badef9bc.png)
![image](https://user-images.githubusercontent.com/44036018/127221679-2e7e5aea-25ad-43c6-b233-4cfb75f15484.png)

**Comment by TuQmano** [comment]
https://dnme-minturdep.github.io/DT4_perfiles/ 

Estaba desactualizado el fix. Acá parece estar ok, al menos en la portada. Queres revisar en los demas @jurricariet ?

**Comment by jurricariet** [comment]
perfecto, quedaron bien los gráficos también
